title: Yasmeen
logo: /assets/img/IMG-20230719-WA0254-CR.jpg
description: Data Analysis | Data Science | Machine Learning

<hr style="border:2px solid gray">

Education
**PgCert., Operational Research, Applied Stats. and Financial Risk (_2023_)**
- Statistics & Data Science (R)
- Computational Methods (Python)
- Time Series Forecasting (R)
- Statistical Programming (R)
- Credit Risk Scoring (Excel & R)

**B.A., Accounting (_2017_)**

<hr style="border:2px solid gray">

Certifications
- Tableau Desktop Certified (_2023_)
- Alteryx Designer Core Certified (_2023_)
<hr style="border:2px solid gray">

Technical Skillset
- Python (Pandas, NumPy, Matplotlib, Seaborn)
- SQL (MySQL Workbench)
- R (+Shiny) 
- Tableau Desktop (+Prep)
- Alteryx Designer
- Microsoft Excel
<hr style="border:2px solid gray">

Work Experience
**Senior Data Analyst (_Jan 2024 - Present_)**
<br>**Data Analyst (_Mar 2022 – Dec 2023_)**

show_download: true
theme: jekyll-theme-minimal
